spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rapidshine-notification-db
    username: springuser
    password: ASDFasdf@1 # Loaded from environment variable

  mail:
    host: smtp.gmail.com
    port: 587
    username: indiawale81@gmail.com
    password: jycdirtatvrcnwdj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username : guest
    password: guest
    listener:
      simple:
        concurrency: 1
        max-concurrency: 5
jwt:
  secret: a-string-secret-at-least-256-bits-long-siddhuertgwerasgagas